service: get-comic-strips

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs12.x

functions:
  comics:
    handler: handler.comics
    events:
      - http:
          path: /comics
          method: get
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-jest-plugin
